# Partial backend config on purpose: the bucket name is generated (random
# suffix) by infra/bootstrap and isn't known until after that's applied, so
# it isn't hardcoded here. Initialize with:
#
#   terraform init -backend-config=backend.hcl
#
# where backend.hcl (gitignored, generated by scripts/bootstrap.sh) contains:
#
#   bucket = "waitly-tfstate-<suffix>"

terraform {
  backend "s3" {
    key          = "waitly/live/terraform.tfstate"
    region       = "us-west-2"
    use_lockfile = true # native S3 conditional-write locking, no DynamoDB table
    encrypt      = true
  }
}
